// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "OpenCV/Features2D/Features2D.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class Features2DHandler : virtual public Features2DIf {
 public:
  Features2DHandler() {
    // Your initialization goes here
  }

  void detect(std::vector<KeyPoint> & _return, const std::string& detector, const  ::Mat& image) {
    // Your implementation goes here
    printf("detect\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<Features2DHandler> handler(new Features2DHandler());
  shared_ptr<TProcessor> processor(new Features2DProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

